### ISSUE TITLE
Comment文件无法获取

### ISSUE THREAD

**Issue by YinHan-Zhang** [GaoakaJie/WeiboSpider_forComments_Reposts_Attitudes#1]
1. attitudes.csv文件已获取
2. 其他的两个文件无法获取，一直打印这个错误` Expecting value: line 1 column 1 (char 0)`
3. 放了一晚上，也没运行结束，一直停留在` Expecting value: line 1 column 1 (char 0)`

**Comment by YinHan-Zhang** [comment]
Traceback (most recent call last):
  File "D:/WeiboSpider_forComments_Reposts_Attitudes/start.py", line 16, in <module>
    parsecomments.main()
  File "D:\\WeiboSpider_forComments_Reposts_Attitudes\parseComments.py", line 52, in main
    new_response = requests.get(new_url, headers=self.headers, params=data).json()
  File "C:\Users\AppData\Roaming\Python\Python38\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by YinHan-Zhang** [comment]
这是cookies给封了么?

**Comment by qq992875076** [comment]
我的也是这个原因，应该不是cookie被封，我换了一个还是报的这个错

**Comment by ZhaoGu0907** [comment]
楼上的解决了么？我的也是这样的问题

**Comment by honglalala** [comment]
朋友们，解决了吗~我也是这样的问题
