### ISSUE TITLE
能否指导一下，每次评论只能获取固定的几百个

### ISSUE THREAD

**Issue by stonecropa** [GaoakaJie/WeiboSpider_forComments_Reposts_Attitudes#2]
*******************************************************************************************

*****第1页评论打印完成*****
Traceback (most recent call last):
  File "/data/lu/yyl/WeiboSpider_forComments_Reposts_Attitudes-main/start.py", line 17, in <module>
    parsecomments.main()
  File "/data/lu/yyl/WeiboSpider_forComments_Reposts_Attitudes-main/parseComments.py", line 69, in main
    max_id = new_response['data']['max_id']
KeyError: 'data'            每次都是这个问题，能否指导一下

**Comment by hws1551556** [comment]
我也是这个问题，不知道是为什么
